from enum import IntEnum


class SignalEnum(IntEnum):
    ENGINE_STARTED = 1
    ENGINE_STOPPED = 2
    SPIDER_OPENED = 3
    SPIDER_IDLE = 4
    SPIDER_CLOSED = 5
    SPIDER_ERROR = 6
    REQUEST_SCHEDULED = 7
    REQUEST_DROPPED = 8
    REQUEST_REACHED_DOWNLOADER = 9
    RESPONSE_RECEIVED = 10
    RESPONSE_DOWNLOADED = 11
    ITEM_SCRAPED = 12
    ITEM_DROPPED = 13
    ITEM_ERROR = 14

    # for backwards compatibility
    STATS_SPIDER_OPENED = SPIDER_OPENED
    STATS_SPIDER_CLOSING = SPIDER_CLOSED
    STATS_SPIDER_CLOSED = SPIDER_CLOSED

    ITEM_PASSED = ITEM_SCRAPED

    REQUEST_RECEIVED = REQUEST_SCHEDULED
